# Site settings
title: Back to School
image: img/home-bg.jpg
logo: img/favicon.png
email: y66ben@gmail.com
description: "The life of a PhD student"
baseurl: ""
author: "Zi Jian Yew"
url: "http://yewzijian.github.io"
# github_username: yewzijian
gaid: UA-XXXXX-X
# disqus_site_id: cleanblogjekyllgithubpages

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
safe: false # safe need to be off for local preview
lsi: false
permalink: pretty
paginate: 5
exclude: ["sass","node_modules","Gruntfile.js","package.json","README.md", "contact.html"]
keep_files: []
